spring.application.name=sgm-spring
spring.datasource.url=jdbc:mysql://localhost:3306/sgm_dilly_sports
spring.datasource.username=root
spring.datasource.password=PIRULITO123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true